package com.jetbrains.php.tools.quality.psalm;

import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.ui.DocumentAdapter;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.ui.components.JBLabel;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jetbrains.php.config.interpreters.PhpInterpreter;
import com.jetbrains.php.config.interpreters.PhpTextFieldWithSdkBasedBrowse;
import com.jetbrains.php.tools.quality.QualityToolConfigurationComboBox;
import com.jetbrains.php.tools.quality.QualityToolsOptionsPanel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import java.awt.Insets;
import java.lang.reflect.Method;
import java.net.URL;
import java.util.ResourceBundle;

import static com.intellij.openapi.vfs.VfsUtil.findFileByURL;
import static com.intellij.openapi.vfs.VfsUtilCore.convertToURL;
import static com.intellij.openapi.vfs.VfsUtilCore.pathToUrl;

public class PsalmOptionsPanel extends QualityToolsOptionsPanel {
  private final JPanel myOptionsPanel;
  private final PhpTextFieldWithSdkBasedBrowse myConfigPathTextField;
  private final JBCheckBox myShowInfoJBCheckBox;
  private final JBCheckBox myFindUnusedCheckbox;
  private final JBCheckBox myFindUnusedSuppressCheckbox;
  private final QualityToolConfigurationComboBox myComboBox;

  public PsalmOptionsPanel(Project project, QualityToolConfigurationComboBox comboBox, Runnable validate) {
    super(project, validate, PsalmQualityToolType.INSTANCE);
    myComboBox = comboBox;
    {
      // GUI initializer generated by IntelliJ IDEA GUI Designer
      // >>> IMPORTANT!! <<<
      // DO NOT EDIT OR ADD ANY CODE HERE!
      myOptionsPanel = new JPanel();
      myOptionsPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 5, 0, 0), -1, -1));
      final Spacer spacer1 = new Spacer();
      myOptionsPanel.add(spacer1, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                                                      GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
      myShowInfoJBCheckBox = new JBCheckBox();
      this.$$$loadButtonText$$$(myShowInfoJBCheckBox, this.$$$getMessageFromBundle$$$("messages/PsalmBundle", "psalm.show.info"));
      myOptionsPanel.add(myShowInfoJBCheckBox, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                   GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                                   null, null, 0, false));
      myFindUnusedCheckbox = new JBCheckBox();
      myFindUnusedCheckbox.setHorizontalAlignment(2);
      this.$$$loadButtonText$$$(myFindUnusedCheckbox, this.$$$getMessageFromBundle$$$("messages/PsalmBundle", "psalm.find.unused"));
      myOptionsPanel.add(myFindUnusedCheckbox, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                                                   GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null,
                                                                   null, null, 0, false));
      myFindUnusedSuppressCheckbox = new JBCheckBox();
      this.$$$loadButtonText$$$(myFindUnusedSuppressCheckbox,
                                this.$$$getMessageFromBundle$$$("messages/PsalmBundle", "psalm.find.unused.supress"));
      myOptionsPanel.add(myFindUnusedSuppressCheckbox,
                         new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                                             GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0,
                                             false));
      final JPanel panel1 = new JPanel();
      panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
      myOptionsPanel.add(panel1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                     GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null,
                                                     null, null, 0, false));
      final JBLabel jBLabel1 = new JBLabel();
      this.$$$loadLabelText$$$(jBLabel1, this.$$$getMessageFromBundle$$$("messages/PsalmBundle", "psalm.configuration.file."));
      panel1.add(jBLabel1,
                 new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                     GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
      myConfigPathTextField = new PhpTextFieldWithSdkBasedBrowse();
      panel1.add(myConfigPathTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                            null, null, null, 0, false));
    }
    PsalmOptionsConfiguration configuration = PsalmOptionsConfiguration.getInstance(project);
    myConfigPathTextField.setText(configuration.getConfig());
    myConfigPathTextField
      .init(project, getSdkAdditionalData(project, comboBox), PsalmBundle.message("psalm.configuration.file"), true, false);
    myShowInfoJBCheckBox.setSelected(configuration.isShowInfo());
    myFindUnusedCheckbox.setSelected(configuration.isFindUnusedCode());
    myFindUnusedSuppressCheckbox.setSelected(configuration.isFindUnusedSuppress());
    myConfigPathTextField.getTextField().getDocument().addDocumentListener(new DocumentAdapter() {
      @Override
      protected void textChanged(@NotNull DocumentEvent e) {
        validate.run();
      }
    });
  }

  private static Method $$$cachedGetBundleMethod$$$ = null;

  /** @noinspection ALL */
  private String $$$getMessageFromBundle$$$(String path, String key) {
    ResourceBundle bundle;
    try {
      Class<?> thisClass = this.getClass();
      if ($$$cachedGetBundleMethod$$$ == null) {
        Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
        $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
      }
      bundle = (ResourceBundle)$$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
    }
    catch (Exception e) {
      bundle = ResourceBundle.getBundle(path);
    }
    return bundle.getString(key);
  }

  /** @noinspection ALL */
  private void $$$loadLabelText$$$(JLabel component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setDisplayedMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  private void $$$loadButtonText$$$(AbstractButton component, String text) {
    StringBuffer result = new StringBuffer();
    boolean haveMnemonic = false;
    char mnemonic = '\0';
    int mnemonicIndex = -1;
    for (int i = 0; i < text.length(); i++) {
      if (text.charAt(i) == '&') {
        i++;
        if (i == text.length()) break;
        if (!haveMnemonic && text.charAt(i) != '&') {
          haveMnemonic = true;
          mnemonic = text.charAt(i);
          mnemonicIndex = result.length();
        }
      }
      result.append(text.charAt(i));
    }
    component.setText(result.toString());
    if (haveMnemonic) {
      component.setMnemonic(mnemonic);
      component.setDisplayedMnemonicIndex(mnemonicIndex);
    }
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() { return myOptionsPanel; }

  @Override
  protected @Nullable String validatePath() {
    PhpInterpreter interpreter = getSelectedInterpreter(myProject, myComboBox);
    if (interpreter != null && interpreter.isRemote()) {
      //TODO: validate remote path?
      return null;
    }
    final URL url = convertToURL(pathToUrl(myConfigPathTextField.getText()));
    if (url == null || findFileByURL(url) == null) {
      return PsalmBundle.message("config.file.doesnt.exist");
    }
    return null;
  }

  @Override
  public JPanel getOptionsPanel() {
    return myOptionsPanel;
  }

  @Override
  public void reset() {
    PsalmOptionsConfiguration configuration = PsalmOptionsConfiguration.getInstance(myProject);
    myConfigPathTextField.setText(configuration.getConfig());
    myShowInfoJBCheckBox.setSelected(configuration.isShowInfo());
    myFindUnusedCheckbox.setSelected(configuration.isFindUnusedCode());
    myFindUnusedSuppressCheckbox.setSelected(configuration.isFindUnusedSuppress());
  }

  @Override
  public boolean isModified() {
    PsalmOptionsConfiguration configuration = PsalmOptionsConfiguration.getInstance(myProject);
    if (!StringUtil.equals(myConfigPathTextField.getText(), configuration.getConfig())) return true;
    if (myShowInfoJBCheckBox.isSelected() != configuration.isShowInfo()) return true;
    if (myFindUnusedCheckbox.isSelected() != configuration.isFindUnusedCode()) return true;
    if (myFindUnusedSuppressCheckbox.isSelected() != configuration.isFindUnusedSuppress()) return true;
    return false;
  }

  @Override
  public void apply() {
    PsalmOptionsConfiguration configuration = PsalmOptionsConfiguration.getInstance(myProject);
    configuration.setConfig(myConfigPathTextField.getText());
    configuration.setFindUnusedCode(myFindUnusedCheckbox.isSelected());
    configuration.setFindUnusedSuppress(myFindUnusedSuppressCheckbox.isSelected());
    configuration.setShowInfo(myShowInfoJBCheckBox.isSelected());
  }
}
